-- Drop existing tables if they exist
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS challenges CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- Create profiles table
CREATE TABLE profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  photo TEXT,
  country TEXT NOT NULL,
  role TEXT NOT NULL,
  business_unit TEXT NOT NULL,
  description TEXT,
  interests TEXT,
  skills JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create challenges table
CREATE TABLE challenges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('public', 'private')),
  suggested_profiles UUID[] DEFAULT '{}',
  participants UUID[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create messages table
CREATE TABLE messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  challenge_id UUID NOT NULL REFERENCES challenges(id) ON DELETE CASCADE,
  sender_profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX idx_messages_challenge_id ON messages(challenge_id);
CREATE INDEX idx_messages_created_at ON messages(created_at);
CREATE INDEX idx_challenges_type ON challenges(type);

-- Insert realistic tech company profiles
INSERT INTO profiles (name, photo, country, role, business_unit, description, interests, skills) VALUES
-- Frontend Developers (1-5)
('Alex Rivera', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'USA', 'Senior Frontend Developer', 'Engineering', 'Specialized in React and modern web technologies', 'Web performance, UI/UX, Open source', '[{"name": "React", "rating": 5}, {"name": "TypeScript", "rating": 5}, {"name": "JavaScript", "rating": 5}, {"name": "CSS", "rating": 4}, {"name": "Next.js", "rating": 4}]'::jsonb),
('Sarah Chen', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', 'China', 'Frontend Developer', 'Engineering', 'Building responsive and accessible web applications', 'Accessibility, Design systems, Animation', '[{"name": "Vue.js", "rating": 4}, {"name": "JavaScript", "rating": 4}, {"name": "HTML", "rating": 5}, {"name": "CSS", "rating": 5}, {"name": "Tailwind", "rating": 4}]'::jsonb),
('Marco Bianchi', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'Italy', 'Frontend Engineer', 'Engineering', 'Focus on component architecture and state management', 'Component libraries, Testing, Performance', '[{"name": "React", "rating": 4}, {"name": "Redux", "rating": 4}, {"name": "JavaScript", "rating": 4}, {"name": "Jest", "rating": 3}, {"name": "Webpack", "rating": 3}]'::jsonb),
('Emma Williams', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'UK', 'UI Developer', 'Engineering', 'Creating pixel-perfect interfaces with attention to detail', 'CSS animations, Design tokens, Responsive design', '[{"name": "CSS", "rating": 5}, {"name": "SASS", "rating": 5}, {"name": "JavaScript", "rating": 3}, {"name": "Figma", "rating": 4}, {"name": "HTML", "rating": 5}]'::jsonb),
('James Park', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'South Korea', 'Senior Frontend Developer', 'Engineering', 'Expert in Angular and enterprise applications', 'Enterprise architecture, RxJS, Testing', '[{"name": "Angular", "rating": 5}, {"name": "TypeScript", "rating": 5}, {"name": "RxJS", "rating": 4}, {"name": "NgRx", "rating": 4}, {"name": "JavaScript", "rating": 4}]'::jsonb),

-- Backend Developers (6-10)
('Carlos Rodriguez', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Spain', 'Senior Backend Developer', 'Engineering', 'Building scalable microservices and APIs', 'Microservices, Cloud architecture, Containers', '[{"name": "Java", "rating": 5}, {"name": "Spring Boot", "rating": 5}, {"name": "Docker", "rating": 4}, {"name": "Kubernetes", "rating": 3}, {"name": "PostgreSQL", "rating": 4}]'::jsonb),
('Nina Petrov', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Russia', 'Backend Developer', 'Engineering', 'Focused on Node.js and serverless architectures', 'Serverless, API design, Event-driven', '[{"name": "Node.js", "rating": 5}, {"name": "JavaScript", "rating": 5}, {"name": "AWS Lambda", "rating": 4}, {"name": "MongoDB", "rating": 4}, {"name": "Express", "rating": 4}]'::jsonb),
('Ahmed Hassan', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', 'Egypt', 'Backend Engineer', 'Engineering', 'Python specialist with focus on data processing', 'Data pipelines, API development, Testing', '[{"name": "Python", "rating": 5}, {"name": "Django", "rating": 4}, {"name": "FastAPI", "rating": 4}, {"name": "PostgreSQL", "rating": 4}, {"name": "Redis", "rating": 3}]'::jsonb),
('Lisa Mueller', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Germany', 'Senior Backend Developer', 'Engineering', 'Expert in distributed systems and databases', 'Distributed systems, Database design, Performance', '[{"name": "Go", "rating": 5}, {"name": "PostgreSQL", "rating": 5}, {"name": "Redis", "rating": 4}, {"name": "gRPC", "rating": 4}, {"name": "Docker", "rating": 4}]'::jsonb),
('Raj Patel', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'India', 'Backend Developer', 'Engineering', 'Building REST APIs and integrations', 'API design, Integration, Documentation', '[{"name": "Java", "rating": 4}, {"name": "Spring", "rating": 4}, {"name": "MySQL", "rating": 4}, {"name": "REST API", "rating": 5}, {"name": "Swagger", "rating": 4}]'::jsonb),

-- Full-Stack Developers (11-13)
('Sophie Martin', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'France', 'Full-Stack Developer', 'Engineering', 'End-to-end development with modern stack', 'Full-stack, DevOps, Cloud', '[{"name": "React", "rating": 4}, {"name": "Node.js", "rating": 4}, {"name": "TypeScript", "rating": 4}, {"name": "PostgreSQL", "rating": 3}, {"name": "AWS", "rating": 3}]'::jsonb),
('Tom Anderson', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'USA', 'Senior Full-Stack Developer', 'Engineering', 'Building complete web applications from scratch', 'Architecture, Databases, Frontend', '[{"name": "JavaScript", "rating": 5}, {"name": "React", "rating": 5}, {"name": "Node.js", "rating": 5}, {"name": "MongoDB", "rating": 4}, {"name": "Express", "rating": 4}]'::jsonb),
('Yuki Tanaka', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'Japan', 'Full-Stack Engineer', 'Engineering', 'Versatile developer comfortable across the stack', 'Web development, APIs, Cloud', '[{"name": "Python", "rating": 4}, {"name": "Vue.js", "rating": 4}, {"name": "Django", "rating": 4}, {"name": "PostgreSQL", "rating": 3}, {"name": "Docker", "rating": 3}]'::jsonb),

-- DevOps Engineers (14-17)
('Michael Brown', 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400', 'Canada', 'DevOps Engineer', 'Infrastructure', 'Automating deployments and infrastructure management', 'CI/CD, Infrastructure as Code, Automation', '[{"name": "Kubernetes", "rating": 5}, {"name": "Docker", "rating": 5}, {"name": "Terraform", "rating": 4}, {"name": "AWS", "rating": 4}, {"name": "Jenkins", "rating": 4}]'::jsonb),
('Anna Kowalski', 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400', 'Poland', 'Senior DevOps Engineer', 'Infrastructure', 'Cloud infrastructure and automation expert', 'Cloud, Security, Monitoring', '[{"name": "AWS", "rating": 5}, {"name": "Terraform", "rating": 5}, {"name": "Python", "rating": 4}, {"name": "Ansible", "rating": 4}, {"name": "Prometheus", "rating": 4}]'::jsonb),
('Diego Santos', 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400', 'Brazil', 'DevOps Engineer', 'Infrastructure', 'Focus on CI/CD pipelines and containerization', 'CI/CD, Containers, Scripting', '[{"name": "GitLab CI", "rating": 4}, {"name": "Docker", "rating": 5}, {"name": "Kubernetes", "rating": 3}, {"name": "Bash", "rating": 4}, {"name": "Azure", "rating": 3}]'::jsonb),
('Zara Khan', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Pakistan', 'Platform Engineer', 'Infrastructure', 'Building developer platforms and tooling', 'Platform engineering, Developer experience, Tools', '[{"name": "Kubernetes", "rating": 4}, {"name": "Go", "rating": 4}, {"name": "Docker", "rating": 5}, {"name": "Helm", "rating": 4}, {"name": "GCP", "rating": 4}]'::jsonb),

-- QA Engineers (18-20)
('Elena Popov', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', 'Bulgaria', 'QA Engineer', 'Quality', 'Ensuring quality through comprehensive testing', 'Test automation, API testing, Performance', '[{"name": "Selenium", "rating": 4}, {"name": "Java", "rating": 3}, {"name": "TestNG", "rating": 4}, {"name": "Postman", "rating": 5}, {"name": "JMeter", "rating": 3}]'::jsonb),
('Kevin Lee', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400', 'Singapore', 'Senior QA Engineer', 'Quality', 'Test automation and quality processes', 'Automation, CI/CD integration, Mobile testing', '[{"name": "Cypress", "rating": 5}, {"name": "JavaScript", "rating": 4}, {"name": "Appium", "rating": 3}, {"name": "Jenkins", "rating": 4}, {"name": "REST API", "rating": 4}]'::jsonb),
('Maria Garcia', 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400', 'Mexico', 'QA Automation Engineer', 'Quality', 'Building robust test frameworks', 'Test frameworks, Code quality, Documentation', '[{"name": "Playwright", "rating": 4}, {"name": "TypeScript", "rating": 4}, {"name": "Python", "rating": 3}, {"name": "pytest", "rating": 4}, {"name": "Git", "rating": 4}]'::jsonb),

-- Product Managers (21-25)
('David Kim', 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400', 'South Korea', 'Senior Product Manager', 'Product', 'Strategic product leader with B2B SaaS experience', 'Product strategy, User research, Data-driven decisions', '[{"name": "Product Strategy", "rating": 5}, {"name": "Agile", "rating": 5}, {"name": "User Research", "rating": 4}, {"name": "Analytics", "rating": 4}, {"name": "Roadmapping", "rating": 5}]'::jsonb),
('Julia Schmidt', 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400', 'Germany', 'Product Manager', 'Product', 'Focus on mobile products and user engagement', 'Mobile products, A/B testing, Growth', '[{"name": "Product Management", "rating": 4}, {"name": "Jira", "rating": 5}, {"name": "SQL", "rating": 3}, {"name": "A/B Testing", "rating": 4}, {"name": "Analytics", "rating": 4}]'::jsonb),
('Robert Taylor', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'Australia', 'Product Owner', 'Product', 'Agile product owner with e-commerce background', 'E-commerce, Agile, Stakeholder management', '[{"name": "Agile", "rating": 5}, {"name": "Scrum", "rating": 5}, {"name": "User Stories", "rating": 5}, {"name": "Backlog Management", "rating": 4}, {"name": "Confluence", "rating": 4}]'::jsonb),
('Priya Sharma', 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400', 'India', 'Technical Product Manager', 'Product', 'Bridging technology and business needs', 'API products, Technical specs, Developer tools', '[{"name": "Product Strategy", "rating": 4}, {"name": "API Design", "rating": 4}, {"name": "Technical Writing", "rating": 5}, {"name": "SQL", "rating": 4}, {"name": "REST API", "rating": 3}]'::jsonb),
('Lucas Silva', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Brazil', 'Product Manager', 'Product', 'Data-driven PM focused on fintech solutions', 'Fintech, Metrics, Customer insights', '[{"name": "Product Management", "rating": 4}, {"name": "Data Analysis", "rating": 4}, {"name": "Mixpanel", "rating": 4}, {"name": "User Research", "rating": 3}, {"name": "Roadmapping", "rating": 4}]'::jsonb),

-- Engineering Managers (26-29)
('Rachel Wong', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'Hong Kong', 'Engineering Manager', 'Engineering', 'Leading frontend engineering teams', 'Team leadership, Technical strategy, Mentoring', '[{"name": "Leadership", "rating": 5}, {"name": "React", "rating": 4}, {"name": "JavaScript", "rating": 4}, {"name": "Team Management", "rating": 5}, {"name": "Agile", "rating": 4}]'::jsonb),
('Stefan Novak', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'Czech Republic', 'Senior Engineering Manager', 'Engineering', 'Managing distributed engineering teams', 'Distributed teams, Scaling, Performance', '[{"name": "Leadership", "rating": 5}, {"name": "System Design", "rating": 4}, {"name": "Team Management", "rating": 5}, {"name": "Hiring", "rating": 4}, {"name": "Strategy", "rating": 4}]'::jsonb),
('Fatima Ali', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'UAE', 'Engineering Manager', 'Engineering', 'Building high-performance backend teams', 'Backend systems, Architecture, Culture', '[{"name": "Leadership", "rating": 5}, {"name": "Java", "rating": 3}, {"name": "Architecture", "rating": 4}, {"name": "Team Building", "rating": 5}, {"name": "Agile", "rating": 4}]'::jsonb),
('Chris Johnson', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'USA', 'Director of Engineering', 'Engineering', 'Leading multiple engineering teams and initiatives', 'Organization building, Strategy, Innovation', '[{"name": "Leadership", "rating": 5}, {"name": "Strategy", "rating": 5}, {"name": "Team Management", "rating": 5}, {"name": "Budgeting", "rating": 4}, {"name": "OKRs", "rating": 5}]'::jsonb),

-- UX/UI Designers (30-35)
('Isabella Rossi', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', 'Italy', 'Senior UX Designer', 'Design', 'User-centered design and research specialist', 'User research, Wireframing, Prototyping', '[{"name": "UX Research", "rating": 5}, {"name": "Figma", "rating": 5}, {"name": "Wireframing", "rating": 5}, {"name": "User Testing", "rating": 4}, {"name": "Information Architecture", "rating": 4}]'::jsonb),
('Olivia Martinez', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Spain', 'UI Designer', 'Design', 'Creating beautiful and functional interfaces', 'Visual design, Design systems, Branding', '[{"name": "UI Design", "rating": 5}, {"name": "Figma", "rating": 5}, {"name": "Adobe XD", "rating": 4}, {"name": "Design Systems", "rating": 4}, {"name": "Typography", "rating": 5}]'::jsonb),
('Noah Anderson', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', 'Sweden', 'Product Designer', 'Design', 'End-to-end product design and strategy', 'Product design, Prototyping, Design thinking', '[{"name": "Product Design", "rating": 5}, {"name": "Figma", "rating": 5}, {"name": "Prototyping", "rating": 5}, {"name": "User Research", "rating": 4}, {"name": "Sketch", "rating": 3}]'::jsonb),
('Mei Lin', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Taiwan', 'UX/UI Designer', 'Design', 'Versatile designer comfortable with full design process', 'Mobile design, Responsive design, Accessibility', '[{"name": "UX Design", "rating": 4}, {"name": "UI Design", "rating": 4}, {"name": "Figma", "rating": 5}, {"name": "Mobile Design", "rating": 4}, {"name": "Accessibility", "rating": 4}]'::jsonb),
('Hassan Ahmed', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'Morocco', 'Design System Lead', 'Design', 'Building and maintaining design systems at scale', 'Design systems, Component libraries, Documentation', '[{"name": "Design Systems", "rating": 5}, {"name": "Figma", "rating": 5}, {"name": "Component Design", "rating": 5}, {"name": "Documentation", "rating": 4}, {"name": "Tokens", "rating": 4}]'::jsonb),
('Chloe Brown', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'UK', 'Interaction Designer', 'Design', 'Specialized in micro-interactions and animations', 'Interaction design, Animation, Prototyping', '[{"name": "Interaction Design", "rating": 5}, {"name": "Prototyping", "rating": 5}, {"name": "After Effects", "rating": 4}, {"name": "Principle", "rating": 4}, {"name": "Figma", "rating": 4}]'::jsonb),

-- Data Scientists (36-40)
('Andrei Volkov', 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400', 'Russia', 'Senior Data Scientist', 'Data & Analytics', 'Machine learning and predictive modeling expert', 'Machine learning, Deep learning, NLP', '[{"name": "Python", "rating": 5}, {"name": "Machine Learning", "rating": 5}, {"name": "TensorFlow", "rating": 4}, {"name": "SQL", "rating": 4}, {"name": "Statistics", "rating": 5}]'::jsonb),
('Aisha Nkrumah', 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400', 'Ghana', 'Data Scientist', 'Data & Analytics', 'Focus on business intelligence and analytics', 'Business intelligence, Data visualization, Analytics', '[{"name": "Python", "rating": 4}, {"name": "SQL", "rating": 5}, {"name": "Tableau", "rating": 5}, {"name": "Statistics", "rating": 4}, {"name": "Pandas", "rating": 4}]'::jsonb),
('Lars Eriksson', 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400', 'Sweden', 'ML Engineer', 'Data & Analytics', 'Building and deploying ML models at scale', 'MLOps, Model deployment, Feature engineering', '[{"name": "Python", "rating": 5}, {"name": "PyTorch", "rating": 5}, {"name": "Docker", "rating": 4}, {"name": "Kubernetes", "rating": 3}, {"name": "MLflow", "rating": 4}]'::jsonb),
('Samantha Lee', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'USA', 'Data Engineer', 'Data & Analytics', 'Building data pipelines and infrastructure', 'Data pipelines, ETL, Big data', '[{"name": "Python", "rating": 4}, {"name": "SQL", "rating": 5}, {"name": "Airflow", "rating": 5}, {"name": "Spark", "rating": 4}, {"name": "AWS", "rating": 4}]'::jsonb),
('Mohammad Rahman', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Bangladesh', 'Data Analyst', 'Data & Analytics', 'Turning data into actionable insights', 'Data analysis, Reporting, Dashboards', '[{"name": "SQL", "rating": 5}, {"name": "Excel", "rating": 5}, {"name": "Power BI", "rating": 4}, {"name": "Python", "rating": 3}, {"name": "Statistics", "rating": 4}]'::jsonb),

-- Mobile Developers (41-45)
('Takeshi Yamamoto', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Japan', 'Senior iOS Developer', 'Engineering', 'Building native iOS applications', 'iOS development, SwiftUI, App architecture', '[{"name": "Swift", "rating": 5}, {"name": "SwiftUI", "rating": 5}, {"name": "UIKit", "rating": 4}, {"name": "Xcode", "rating": 5}, {"name": "iOS SDK", "rating": 5}]'::jsonb),
('Ana Costa', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', 'Portugal', 'Android Developer', 'Engineering', 'Native Android app development specialist', 'Android, Kotlin, Material Design', '[{"name": "Kotlin", "rating": 5}, {"name": "Android SDK", "rating": 5}, {"name": "Jetpack Compose", "rating": 4}, {"name": "Java", "rating": 4}, {"name": "Android Studio", "rating": 5}]'::jsonb),
('Miguel Torres', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400', 'Argentina', 'React Native Developer', 'Engineering', 'Cross-platform mobile development', 'React Native, Mobile apps, Performance', '[{"name": "React Native", "rating": 5}, {"name": "JavaScript", "rating": 5}, {"name": "TypeScript", "rating": 4}, {"name": "Redux", "rating": 4}, {"name": "Mobile Dev", "rating": 5}]'::jsonb),
('Sophia Andersson', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'Denmark', 'Flutter Developer', 'Engineering', 'Building beautiful cross-platform apps', 'Flutter, Dart, Mobile UI', '[{"name": "Flutter", "rating": 5}, {"name": "Dart", "rating": 5}, {"name": "Firebase", "rating": 4}, {"name": "Mobile Design", "rating": 4}, {"name": "State Management", "rating": 4}]'::jsonb),
('Ben Williams', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'New Zealand', 'Mobile Architect', 'Engineering', 'Architecting mobile solutions at scale', 'Mobile architecture, Performance, Best practices', '[{"name": "iOS", "rating": 4}, {"name": "Android", "rating": 4}, {"name": "Architecture", "rating": 5}, {"name": "Performance", "rating": 5}, {"name": "CI/CD", "rating": 4}]'::jsonb),

-- Security Engineers (46-49)
('Viktor Ivanov', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'Ukraine', 'Security Engineer', 'Security', 'Application security and penetration testing', 'AppSec, Pentesting, Security audits', '[{"name": "Security", "rating": 5}, {"name": "Penetration Testing", "rating": 5}, {"name": "OWASP", "rating": 4}, {"name": "Python", "rating": 4}, {"name": "Burp Suite", "rating": 4}]'::jsonb),
('Leila Hassan', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Lebanon', 'Cloud Security Engineer', 'Security', 'Securing cloud infrastructure and applications', 'Cloud security, IAM, Compliance', '[{"name": "AWS Security", "rating": 5}, {"name": "IAM", "rating": 5}, {"name": "Security Auditing", "rating": 4}, {"name": "Compliance", "rating": 4}, {"name": "Terraform", "rating": 3}]'::jsonb),
('Ryan Murphy', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Ireland', 'Senior Security Engineer', 'Security', 'Building secure systems and processes', 'Secure coding, Threat modeling, Incident response', '[{"name": "Security", "rating": 5}, {"name": "Threat Modeling", "rating": 5}, {"name": "Incident Response", "rating": 4}, {"name": "Network Security", "rating": 4}, {"name": "SIEM", "rating": 3}]'::jsonb),
('Yara Mansour', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Jordan', 'DevSecOps Engineer', 'Security', 'Integrating security into DevOps pipelines', 'DevSecOps, SAST/DAST, Container security', '[{"name": "DevSecOps", "rating": 5}, {"name": "Docker Security", "rating": 4}, {"name": "SAST", "rating": 4}, {"name": "Kubernetes Security", "rating": 4}, {"name": "CI/CD Security", "rating": 5}]'::jsonb),

-- Architects (50-53)
('Thomas Weber', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', 'Switzerland', 'Solutions Architect', 'Architecture', 'Designing enterprise solutions and systems', 'System design, Cloud architecture, Integration', '[{"name": "System Design", "rating": 5}, {"name": "AWS", "rating": 5}, {"name": "Microservices", "rating": 5}, {"name": "Architecture Patterns", "rating": 5}, {"name": "API Design", "rating": 4}]'::jsonb),
('Priya Gupta', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'India', 'Cloud Architect', 'Architecture', 'Expert in cloud-native architectures', 'Cloud native, Multi-cloud, Migration', '[{"name": "AWS", "rating": 5}, {"name": "Azure", "rating": 4}, {"name": "Cloud Architecture", "rating": 5}, {"name": "Serverless", "rating": 4}, {"name": "Migration", "rating": 4}]'::jsonb),
('Marco Ferrari', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'Italy', 'Enterprise Architect', 'Architecture', 'Aligning technology with business strategy', 'Enterprise architecture, Strategy, Governance', '[{"name": "Enterprise Architecture", "rating": 5}, {"name": "TOGAF", "rating": 4}, {"name": "Strategy", "rating": 5}, {"name": "Business Analysis", "rating": 4}, {"name": "Governance", "rating": 4}]'::jsonb),
('Sarah O''Connor', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Ireland', 'Data Architect', 'Architecture', 'Designing scalable data platforms', 'Data architecture, Data modeling, Big data', '[{"name": "Data Architecture", "rating": 5}, {"name": "Data Modeling", "rating": 5}, {"name": "SQL", "rating": 5}, {"name": "Big Data", "rating": 4}, {"name": "Cloud Data", "rating": 4}]'::jsonb),

-- Scrum Masters & Agile Coaches (54-57)
('Henrik Jensen', 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400', 'Norway', 'Scrum Master', 'Agile', 'Facilitating agile teams and removing impediments', 'Scrum, Facilitation, Team coaching', '[{"name": "Scrum", "rating": 5}, {"name": "Agile", "rating": 5}, {"name": "Facilitation", "rating": 5}, {"name": "Coaching", "rating": 4}, {"name": "Jira", "rating": 5}]'::jsonb),
('Carmen Rodriguez', 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400', 'Chile', 'Agile Coach', 'Agile', 'Transforming organizations to agile ways of working', 'Agile transformation, Coaching, Change management', '[{"name": "Agile Coaching", "rating": 5}, {"name": "Scrum", "rating": 5}, {"name": "SAFe", "rating": 4}, {"name": "Change Management", "rating": 5}, {"name": "Leadership", "rating": 4}]'::jsonb),
('Dmitri Sokolov', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Estonia', 'Senior Scrum Master', 'Agile', 'Leading multiple scrum teams', 'Scaled agile, Team dynamics, Metrics', '[{"name": "Scrum", "rating": 5}, {"name": "Kanban", "rating": 4}, {"name": "Agile Metrics", "rating": 5}, {"name": "Team Building", "rating": 5}, {"name": "Conflict Resolution", "rating": 4}]'::jsonb),
('Amara Okafor', 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400', 'Nigeria', 'Delivery Manager', 'Agile', 'Managing delivery and stakeholder expectations', 'Delivery management, Stakeholders, Planning', '[{"name": "Project Management", "rating": 5}, {"name": "Agile", "rating": 5}, {"name": "Stakeholder Management", "rating": 5}, {"name": "Risk Management", "rating": 4}, {"name": "Reporting", "rating": 4}]'::jsonb),

-- Technical Writers & Documentation (58-60)
('Emily Thompson', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'Canada', 'Technical Writer', 'Documentation', 'Creating clear technical documentation', 'Technical writing, API docs, User guides', '[{"name": "Technical Writing", "rating": 5}, {"name": "API Documentation", "rating": 5}, {"name": "Markdown", "rating": 5}, {"name": "Git", "rating": 4}, {"name": "Documentation Tools", "rating": 4}]'::jsonb),
('Kenji Sato', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'Japan', 'Developer Advocate', 'Developer Relations', 'Building developer communities and content', 'Developer relations, Content creation, Public speaking', '[{"name": "Technical Writing", "rating": 4}, {"name": "Public Speaking", "rating": 5}, {"name": "Community Building", "rating": 5}, {"name": "Content Creation", "rating": 5}, {"name": "JavaScript", "rating": 4}]'::jsonb),
('Laura Fontana', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', 'Italy', 'Documentation Engineer', 'Documentation', 'Building documentation systems and processes', 'Docs as code, Content strategy, Tools', '[{"name": "Documentation", "rating": 5}, {"name": "Docs as Code", "rating": 5}, {"name": "Python", "rating": 3}, {"name": "Sphinx", "rating": 4}, {"name": "Git", "rating": 4}]'::jsonb),

-- SRE/Infrastructure (61-65)
('Oliver Schmidt', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'Germany', 'Site Reliability Engineer', 'Infrastructure', 'Ensuring system reliability and performance', 'SRE, Monitoring, Incident management', '[{"name": "SRE", "rating": 5}, {"name": "Kubernetes", "rating": 5}, {"name": "Prometheus", "rating": 5}, {"name": "Grafana", "rating": 4}, {"name": "Python", "rating": 4}]'::jsonb),
('Natasha Petrov', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Russia', 'Infrastructure Engineer', 'Infrastructure', 'Building and maintaining cloud infrastructure', 'Infrastructure, Automation, Cloud', '[{"name": "Terraform", "rating": 5}, {"name": "AWS", "rating": 5}, {"name": "Linux", "rating": 5}, {"name": "Ansible", "rating": 4}, {"name": "Networking", "rating": 4}]'::jsonb),
('Jorge Mendez', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Colombia', 'Cloud Engineer', 'Infrastructure', 'Multi-cloud infrastructure specialist', 'Cloud, Migration, Optimization', '[{"name": "AWS", "rating": 4}, {"name": "GCP", "rating": 4}, {"name": "Azure", "rating": 3}, {"name": "Terraform", "rating": 5}, {"name": "Docker", "rating": 4}]'::jsonb),
('Ingrid Larsen', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', 'Finland', 'Senior SRE', 'Infrastructure', 'Leading reliability engineering practices', 'SRE practices, Incident response, SLO/SLI', '[{"name": "SRE", "rating": 5}, {"name": "Observability", "rating": 5}, {"name": "Incident Management", "rating": 5}, {"name": "Python", "rating": 4}, {"name": "Go", "rating": 3}]'::jsonb),
('Antonio Lopez', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', 'Mexico', 'Network Engineer', 'Infrastructure', 'Network design and troubleshooting', 'Networking, Security, Performance', '[{"name": "Networking", "rating": 5}, {"name": "Cisco", "rating": 4}, {"name": "Firewalls", "rating": 4}, {"name": "VPN", "rating": 4}, {"name": "Load Balancing", "rating": 4}]'::jsonb),

-- Business Analysts (66-69)
('Hannah Cohen', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Israel', 'Business Analyst', 'Product', 'Bridging business and technology', 'Requirements gathering, Process analysis, Documentation', '[{"name": "Business Analysis", "rating": 5}, {"name": "Requirements Gathering", "rating": 5}, {"name": "SQL", "rating": 4}, {"name": "Process Modeling", "rating": 4}, {"name": "Jira", "rating": 4}]'::jsonb),
('Pierre Dubois', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'France', 'Senior Business Analyst', 'Product', 'Complex systems analysis and optimization', 'System analysis, Optimization, Stakeholders', '[{"name": "Business Analysis", "rating": 5}, {"name": "Data Analysis", "rating": 4}, {"name": "Process Improvement", "rating": 5}, {"name": "UML", "rating": 4}, {"name": "Agile", "rating": 4}]'::jsonb),
('Kavita Menon', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Singapore', 'Technical Business Analyst', 'Product', 'Technical requirements and system integration', 'Technical specs, Integration, APIs', '[{"name": "Business Analysis", "rating": 4}, {"name": "SQL", "rating": 5}, {"name": "API Analysis", "rating": 4}, {"name": "Technical Writing", "rating": 4}, {"name": "Data Modeling", "rating": 3}]'::jsonb),
('Marcus Johnson', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'South Africa', 'Product Analyst', 'Product', 'Data-driven product insights and optimization', 'Product analytics, A/B testing, Metrics', '[{"name": "Product Analytics", "rating": 5}, {"name": "SQL", "rating": 5}, {"name": "Google Analytics", "rating": 5}, {"name": "A/B Testing", "rating": 4}, {"name": "Data Visualization", "rating": 4}]'::jsonb),

-- Specialized Developers (70-80)
('Wei Zhang', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400', 'China', 'Blockchain Developer', 'Engineering', 'Building decentralized applications', 'Blockchain, Smart contracts, Web3', '[{"name": "Solidity", "rating": 5}, {"name": "Ethereum", "rating": 5}, {"name": "Web3.js", "rating": 4}, {"name": "JavaScript", "rating": 4}, {"name": "Smart Contracts", "rating": 5}]'::jsonb),
('Gabriela Santos', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Brazil', 'Game Developer', 'Engineering', 'Creating engaging game experiences', 'Game development, Unity, Game design', '[{"name": "Unity", "rating": 5}, {"name": "C#", "rating": 5}, {"name": "Game Design", "rating": 4}, {"name": "3D Graphics", "rating": 3}, {"name": "Mobile Games", "rating": 4}]'::jsonb),
('Liam Murphy', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Ireland', 'Embedded Systems Engineer', 'Engineering', 'Low-level programming and hardware integration', 'Embedded systems, C/C++, Hardware', '[{"name": "C", "rating": 5}, {"name": "C++", "rating": 5}, {"name": "Embedded Systems", "rating": 5}, {"name": "RTOS", "rating": 4}, {"name": "Hardware", "rating": 4}]'::jsonb),
('Anika Patel', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'India', 'Computer Vision Engineer', 'Engineering', 'Developing computer vision and image processing solutions', 'Computer vision, Deep learning, OpenCV', '[{"name": "Python", "rating": 5}, {"name": "OpenCV", "rating": 5}, {"name": "TensorFlow", "rating": 4}, {"name": "Computer Vision", "rating": 5}, {"name": "Image Processing", "rating": 4}]'::jsonb),
('Erik Johansson', 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400', 'Sweden', 'Graphics Programmer', 'Engineering', 'Real-time graphics and rendering', 'Graphics programming, Shaders, Performance', '[{"name": "C++", "rating": 5}, {"name": "OpenGL", "rating": 5}, {"name": "Vulkan", "rating": 4}, {"name": "Shaders", "rating": 5}, {"name": "3D Math", "rating": 5}]'::jsonb),
('Yuki Nakamura', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'Japan', 'NLP Engineer', 'Engineering', 'Natural language processing and text analytics', 'NLP, Machine learning, Text processing', '[{"name": "Python", "rating": 5}, {"name": "NLP", "rating": 5}, {"name": "Transformers", "rating": 4}, {"name": "spaCy", "rating": 4}, {"name": "Machine Learning", "rating": 4}]'::jsonb),
('Isabella Cruz', 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400', 'Philippines', 'Salesforce Developer', 'Engineering', 'Customizing and extending Salesforce platform', 'Salesforce, Apex, Lightning', '[{"name": "Salesforce", "rating": 5}, {"name": "Apex", "rating": 5}, {"name": "Lightning", "rating": 4}, {"name": "SOQL", "rating": 4}, {"name": "Integration", "rating": 4}]'::jsonb),
('Sebastian Mueller', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'Austria', 'SAP Developer', 'Engineering', 'Enterprise SAP solutions development', 'SAP, ABAP, Enterprise systems', '[{"name": "SAP", "rating": 5}, {"name": "ABAP", "rating": 5}, {"name": "SAP Fiori", "rating": 4}, {"name": "Integration", "rating": 4}, {"name": "SQL", "rating": 3}]'::jsonb),
('Maya Patel', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'UAE', '.NET Developer', 'Engineering', 'Building enterprise applications with .NET', '.NET, C#, Azure', '[{"name": "C#", "rating": 5}, {"name": ".NET Core", "rating": 5}, {"name": "ASP.NET", "rating": 5}, {"name": "Azure", "rating": 4}, {"name": "SQL Server", "rating": 4}]'::jsonb),
('Jan Kowalski', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Poland', 'Ruby Developer', 'Engineering', 'Web development with Ruby on Rails', 'Ruby, Rails, Web development', '[{"name": "Ruby", "rating": 5}, {"name": "Rails", "rating": 5}, {"name": "PostgreSQL", "rating": 4}, {"name": "JavaScript", "rating": 3}, {"name": "RSpec", "rating": 4}]'::jsonb),
('Fatima Al-Rashid', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Saudi Arabia', 'PHP Developer', 'Engineering', 'Building web applications with PHP and Laravel', 'PHP, Laravel, MySQL', '[{"name": "PHP", "rating": 5}, {"name": "Laravel", "rating": 5}, {"name": "MySQL", "rating": 5}, {"name": "JavaScript", "rating": 3}, {"name": "REST API", "rating": 4}]'::jsonb),

-- More Frontend Developers (81-90)
('Lucas Anderson', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Norway', 'Frontend Developer', 'Engineering', 'Creating modern web interfaces', 'React, Performance, Accessibility', '[{"name": "React", "rating": 4}, {"name": "JavaScript", "rating": 5}, {"name": "HTML", "rating": 5}, {"name": "CSS", "rating": 4}, {"name": "Git", "rating": 4}]'::jsonb),
('Sofia Fernandez', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Argentina', 'UI Engineer', 'Engineering', 'Specialized in UI components and design systems', 'UI components, Storybook, Testing', '[{"name": "React", "rating": 5}, {"name": "Storybook", "rating": 5}, {"name": "TypeScript", "rating": 4}, {"name": "Testing Library", "rating": 4}, {"name": "CSS", "rating": 5}]'::jsonb),
('Daniel Kim', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'USA', 'Web Developer', 'Engineering', 'Building responsive websites', 'Web development, Responsive design, SEO', '[{"name": "HTML", "rating": 5}, {"name": "CSS", "rating": 5}, {"name": "JavaScript", "rating": 4}, {"name": "SEO", "rating": 4}, {"name": "WordPress", "rating": 3}]'::jsonb),
('Anna Kowalczyk', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', 'Poland', 'Frontend Engineer', 'Engineering', 'Modern JavaScript applications', 'JavaScript, Build tools, Testing', '[{"name": "JavaScript", "rating": 5}, {"name": "Webpack", "rating": 4}, {"name": "Vite", "rating": 4}, {"name": "Jest", "rating": 4}, {"name": "TypeScript", "rating": 3}]'::jsonb),
('Mohamed El-Sayed', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', 'Egypt', 'React Developer', 'Engineering', 'Expert in React ecosystem', 'React, Redux, Hooks', '[{"name": "React", "rating": 5}, {"name": "Redux", "rating": 5}, {"name": "React Hooks", "rating": 5}, {"name": "TypeScript", "rating": 4}, {"name": "Testing", "rating": 4}]'::jsonb),
('Lucia Romano', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Italy', 'Vue.js Developer', 'Engineering', 'Building Vue.js applications', 'Vue.js, Composition API, Pinia', '[{"name": "Vue.js", "rating": 5}, {"name": "JavaScript", "rating": 5}, {"name": "Pinia", "rating": 4}, {"name": "Nuxt.js", "rating": 4}, {"name": "CSS", "rating": 4}]'::jsonb),
('Henrik Petersen', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Denmark', 'Frontend Lead', 'Engineering', 'Leading frontend development teams', 'Leadership, Architecture, Best practices', '[{"name": "React", "rating": 5}, {"name": "Leadership", "rating": 4}, {"name": "Architecture", "rating": 5}, {"name": "TypeScript", "rating": 5}, {"name": "Code Review", "rating": 5}]'::jsonb),
('Amina Ibrahim', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Kenya', 'Web Developer', 'Engineering', 'Full-cycle web development', 'Web development, Responsive, Modern CSS', '[{"name": "HTML", "rating": 5}, {"name": "CSS", "rating": 5}, {"name": "JavaScript", "rating": 4}, {"name": "Tailwind", "rating": 5}, {"name": "React", "rating": 3}]'::jsonb),
('Pavel Novotny', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Czech Republic', 'JavaScript Developer', 'Engineering', 'Pure JavaScript specialist', 'JavaScript, Vanilla JS, Performance', '[{"name": "JavaScript", "rating": 5}, {"name": "TypeScript", "rating": 4}, {"name": "DOM", "rating": 5}, {"name": "Performance", "rating": 4}, {"name": "Testing", "rating": 3}]'::jsonb),
('Grace Okonkwo', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'Nigeria', 'Angular Developer', 'Engineering', 'Enterprise Angular applications', 'Angular, RxJS, NgRx', '[{"name": "Angular", "rating": 5}, {"name": "TypeScript", "rating": 5}, {"name": "RxJS", "rating": 4}, {"name": "NgRx", "rating": 4}, {"name": "Testing", "rating": 4}]'::jsonb),

-- More Backend Developers (91-100)
('Arjun Krishnan', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'India', 'Backend Engineer', 'Engineering', 'Scalable backend systems', 'Microservices, Databases, APIs', '[{"name": "Java", "rating": 5}, {"name": "Spring Boot", "rating": 5}, {"name": "PostgreSQL", "rating": 4}, {"name": "Redis", "rating": 4}, {"name": "Kafka", "rating": 3}]'::jsonb),
('Elena Vasquez', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Venezuela', 'Node.js Developer', 'Engineering', 'Building APIs with Node.js', 'Node.js, Express, MongoDB', '[{"name": "Node.js", "rating": 5}, {"name": "Express", "rating": 5}, {"name": "MongoDB", "rating": 5}, {"name": "JavaScript", "rating": 5}, {"name": "REST API", "rating": 5}]'::jsonb),
('Takashi Suzuki', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'Japan', 'Python Backend Developer', 'Engineering', 'Python APIs and services', 'Python, FastAPI, PostgreSQL', '[{"name": "Python", "rating": 5}, {"name": "FastAPI", "rating": 5}, {"name": "PostgreSQL", "rating": 4}, {"name": "Docker", "rating": 4}, {"name": "REST API", "rating": 5}]'::jsonb),
('Marta Silva', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'Portugal', 'API Developer', 'Engineering', 'RESTful and GraphQL APIs', 'API design, GraphQL, Documentation', '[{"name": "Node.js", "rating": 4}, {"name": "GraphQL", "rating": 5}, {"name": "REST API", "rating": 5}, {"name": "API Design", "rating": 5}, {"name": "Apollo", "rating": 4}]'::jsonb),
('Ivan Petrov', 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400', 'Bulgaria', 'Backend Developer', 'Engineering', 'Enterprise Java applications', 'Java, Spring, Microservices', '[{"name": "Java", "rating": 5}, {"name": "Spring", "rating": 5}, {"name": "Hibernate", "rating": 4}, {"name": "MySQL", "rating": 4}, {"name": "Docker", "rating": 3}]'::jsonb),
('Zoe Williams', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', 'UK', 'Go Developer', 'Engineering', 'High-performance Go services', 'Go, Concurrency, Performance', '[{"name": "Go", "rating": 5}, {"name": "gRPC", "rating": 4}, {"name": "PostgreSQL", "rating": 4}, {"name": "Docker", "rating": 4}, {"name": "Kubernetes", "rating": 3}]'::jsonb),
('Ali Hassan', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400', 'Tunisia', 'Django Developer', 'Engineering', 'Django web applications', 'Django, Python, Web development', '[{"name": "Django", "rating": 5}, {"name": "Python", "rating": 5}, {"name": "PostgreSQL", "rating": 4}, {"name": "REST Framework", "rating": 5}, {"name": "Celery", "rating": 3}]'::jsonb),
('Katrina Olsen', 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400', 'Sweden', 'Rust Developer', 'Engineering', 'Systems programming with Rust', 'Rust, Performance, Systems', '[{"name": "Rust", "rating": 5}, {"name": "Systems Programming", "rating": 5}, {"name": "Performance", "rating": 5}, {"name": "C++", "rating": 4}, {"name": "Docker", "rating": 3}]'::jsonb),
('Diego Morales', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Peru', 'Microservices Developer', 'Engineering', 'Distributed microservices architectures', 'Microservices, Event-driven, Messaging', '[{"name": "Microservices", "rating": 5}, {"name": "Java", "rating": 5}, {"name": "Kafka", "rating": 5}, {"name": "Docker", "rating": 4}, {"name": "Kubernetes", "rating": 4}]'::jsonb),
('Nina Johansson', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Finland', 'Scala Developer', 'Engineering', 'Functional programming with Scala', 'Scala, Functional programming, Akka', '[{"name": "Scala", "rating": 5}, {"name": "Akka", "rating": 4}, {"name": "Functional Programming", "rating": 5}, {"name": "Spark", "rating": 4}, {"name": "Kafka", "rating": 4}]'::jsonb),

-- More QA Engineers (101-106)
('Robert Chang', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'Taiwan', 'QA Lead', 'Quality', 'Leading quality assurance teams', 'QA leadership, Strategy, Automation', '[{"name": "QA Leadership", "rating": 5}, {"name": "Test Strategy", "rating": 5}, {"name": "Selenium", "rating": 4}, {"name": "CI/CD", "rating": 4}, {"name": "Agile", "rating": 5}]'::jsonb),
('Camila Rodrigues', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', 'Brazil', 'Test Engineer', 'Quality', 'Manual and automated testing', 'Testing, Automation, Bug tracking', '[{"name": "Manual Testing", "rating": 5}, {"name": "Test Cases", "rating": 5}, {"name": "Jira", "rating": 5}, {"name": "Selenium", "rating": 3}, {"name": "API Testing", "rating": 4}]'::jsonb),
('Ahmed Zaki', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Jordan', 'Performance Test Engineer', 'Quality', 'Performance and load testing', 'Performance testing, JMeter, LoadRunner', '[{"name": "JMeter", "rating": 5}, {"name": "Performance Testing", "rating": 5}, {"name": "Load Testing", "rating": 5}, {"name": "Gatling", "rating": 4}, {"name": "Monitoring", "rating": 4}]'::jsonb),
('Sasha Ivanov', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Ukraine', 'Mobile QA Engineer', 'Quality', 'Mobile app testing specialist', 'Mobile testing, Appium, Test automation', '[{"name": "Mobile Testing", "rating": 5}, {"name": "Appium", "rating": 5}, {"name": "XCUITest", "rating": 4}, {"name": "Espresso", "rating": 4}, {"name": "CI/CD", "rating": 3}]'::jsonb),
('Lisa Chen', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Singapore', 'QA Architect', 'Quality', 'Designing test frameworks and strategies', 'Test architecture, Framework design, Strategy', '[{"name": "Test Architecture", "rating": 5}, {"name": "Framework Design", "rating": 5}, {"name": "Java", "rating": 4}, {"name": "Selenium", "rating": 5}, {"name": "CI/CD", "rating": 4}]'::jsonb),
('Oscar Martinez', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', 'Spain', 'Security Tester', 'Quality', 'Security and penetration testing', 'Security testing, OWASP, Vulnerability assessment', '[{"name": "Security Testing", "rating": 5}, {"name": "OWASP", "rating": 5}, {"name": "Penetration Testing", "rating": 4}, {"name": "Burp Suite", "rating": 4}, {"name": "Vulnerability Scanning", "rating": 5}]'::jsonb),

-- More Product & Design (107-115)
('Emma Larsson', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Sweden', 'UX Researcher', 'Design', 'Understanding user needs through research', 'User research, Interviews, Usability testing', '[{"name": "User Research", "rating": 5}, {"name": "Usability Testing", "rating": 5}, {"name": "Interviews", "rating": 5}, {"name": "Surveys", "rating": 4}, {"name": "Data Analysis", "rating": 4}]'::jsonb),
('Karim Mansour', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'Lebanon', 'Product Designer', 'Design', 'Creating delightful product experiences', 'Product design, User flows, Prototyping', '[{"name": "Product Design", "rating": 5}, {"name": "Figma", "rating": 5}, {"name": "User Flows", "rating": 5}, {"name": "Prototyping", "rating": 5}, {"name": "Design Thinking", "rating": 4}]'::jsonb),
('Ingrid Bakke', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'Norway', 'Visual Designer', 'Design', 'Crafting beautiful visual designs', 'Visual design, Branding, Illustration', '[{"name": "Visual Design", "rating": 5}, {"name": "Illustrator", "rating": 5}, {"name": "Photoshop", "rating": 5}, {"name": "Branding", "rating": 4}, {"name": "Figma", "rating": 4}]'::jsonb),
('James Taylor', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'Canada', 'Motion Designer', 'Design', 'Creating engaging animations', 'Motion design, Animation, After Effects', '[{"name": "After Effects", "rating": 5}, {"name": "Motion Design", "rating": 5}, {"name": "Animation", "rating": 5}, {"name": "Lottie", "rating": 4}, {"name": "Cinema 4D", "rating": 3}]'::jsonb),
('Valentina Rossi', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'Italy', 'Service Designer', 'Design', 'Designing end-to-end service experiences', 'Service design, Journey mapping, Strategy', '[{"name": "Service Design", "rating": 5}, {"name": "Journey Mapping", "rating": 5}, {"name": "Workshop Facilitation", "rating": 4}, {"name": "Research", "rating": 4}, {"name": "Strategy", "rating": 4}]'::jsonb),
('Andre Nkomo', 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400', 'South Africa', 'Product Manager', 'Product', 'Technical product management', 'Product management, APIs, Developer tools', '[{"name": "Product Management", "rating": 5}, {"name": "Technical Strategy", "rating": 4}, {"name": "Roadmapping", "rating": 5}, {"name": "APIs", "rating": 3}, {"name": "Agile", "rating": 5}]'::jsonb),
('Maya Stein', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', 'Austria', 'Growth PM', 'Product', 'Product-led growth strategies', 'Growth, Experiments, Metrics', '[{"name": "Growth Strategy", "rating": 5}, {"name": "A/B Testing", "rating": 5}, {"name": "Analytics", "rating": 5}, {"name": "Product Management", "rating": 4}, {"name": "SQL", "rating": 4}]'::jsonb),
('Connor O''Brien', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Ireland', 'Platform PM', 'Product', 'Developer platforms and tools', 'Platform products, Developer experience, APIs', '[{"name": "Product Management", "rating": 5}, {"name": "Platform Strategy", "rating": 5}, {"name": "Developer Experience", "rating": 5}, {"name": "APIs", "rating": 4}, {"name": "Technical Writing", "rating": 3}]'::jsonb),
('Yara Khalil', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Syria', 'Associate Product Manager', 'Product', 'Learning product management', 'Product basics, Analytics, User stories', '[{"name": "Product Management", "rating": 3}, {"name": "User Stories", "rating": 4}, {"name": "Analytics", "rating": 3}, {"name": "Jira", "rating": 4}, {"name": "Agile", "rating": 4}]'::jsonb),

-- More Data Roles (116-120)
('Boris Sokolov', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400', 'Russia', 'Data Platform Engineer', 'Data & Analytics', 'Building scalable data platforms', 'Data platforms, ETL, Infrastructure', '[{"name": "Python", "rating": 5}, {"name": "Airflow", "rating": 5}, {"name": "Spark", "rating": 5}, {"name": "SQL", "rating": 5}, {"name": "Kubernetes", "rating": 4}]'::jsonb),
('Fatima Zahra', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Morocco', 'BI Developer', 'Data & Analytics', 'Business intelligence and reporting', 'BI, Reporting, Dashboards', '[{"name": "Power BI", "rating": 5}, {"name": "SQL", "rating": 5}, {"name": "DAX", "rating": 5}, {"name": "Data Modeling", "rating": 4}, {"name": "Excel", "rating": 5}]'::jsonb),
('Luca Romano', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Italy', 'Analytics Engineer', 'Data & Analytics', 'Building data models and transformations', 'dbt, SQL, Data modeling', '[{"name": "SQL", "rating": 5}, {"name": "dbt", "rating": 5}, {"name": "Data Modeling", "rating": 5}, {"name": "Python", "rating": 4}, {"name": "Git", "rating": 4}]'::jsonb),
('Nora Hassan', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Sudan', 'Data Scientist', 'Data & Analytics', 'Predictive analytics and modeling', 'Statistics, ML, Predictive analytics', '[{"name": "Python", "rating": 5}, {"name": "Statistics", "rating": 5}, {"name": "Scikit-learn", "rating": 5}, {"name": "SQL", "rating": 4}, {"name": "R", "rating": 3}]'::jsonb),
('Oleksandr Koval', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Ukraine', 'ML Ops Engineer', 'Data & Analytics', 'MLOps and model deployment', 'MLOps, Model deployment, CI/CD', '[{"name": "MLOps", "rating": 5}, {"name": "Python", "rating": 5}, {"name": "Docker", "rating": 5}, {"name": "Kubernetes", "rating": 4}, {"name": "AWS", "rating": 4}]'::jsonb),

-- More DevOps & SRE (121-135)
('Gabriel Costa', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'Brazil', 'DevOps Specialist', 'Infrastructure', 'CI/CD and automation', 'CI/CD, Automation, Scripting', '[{"name": "Jenkins", "rating": 5}, {"name": "GitLab CI", "rating": 5}, {"name": "Bash", "rating": 5}, {"name": "Python", "rating": 4}, {"name": "Docker", "rating": 5}]'::jsonb),
('Aisha Mohammed', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Ethiopia', 'Cloud DevOps Engineer', 'Infrastructure', 'Cloud infrastructure automation', 'Cloud, IaC, Automation', '[{"name": "AWS", "rating": 5}, {"name": "Terraform", "rating": 5}, {"name": "CloudFormation", "rating": 4}, {"name": "Python", "rating": 4}, {"name": "Git", "rating": 5}]'::jsonb),
('Bjorn Larsen', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'Iceland', 'Release Engineer', 'Infrastructure', 'Managing software releases', 'Release management, CI/CD, Versioning', '[{"name": "Release Management", "rating": 5}, {"name": "Git", "rating": 5}, {"name": "Jenkins", "rating": 5}, {"name": "Scripting", "rating": 4}, {"name": "Docker", "rating": 4}]'::jsonb),
('Mei Wang', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'China', 'Build Engineer', 'Infrastructure', 'Build systems and pipelines', 'Build systems, CI/CD, Tools', '[{"name": "Maven", "rating": 5}, {"name": "Gradle", "rating": 5}, {"name": "CI/CD", "rating": 5}, {"name": "Java", "rating": 4}, {"name": "Jenkins", "rating": 5}]'::jsonb),
('Santiago Ruiz', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Chile', 'Platform SRE', 'Infrastructure', 'Platform reliability engineering', 'SRE, Platforms, Observability', '[{"name": "Kubernetes", "rating": 5}, {"name": "Observability", "rating": 5}, {"name": "SRE", "rating": 5}, {"name": "Go", "rating": 4}, {"name": "Terraform", "rating": 4}]'::jsonb),
('Chiara Bianchi', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Italy', 'Monitoring Engineer', 'Infrastructure', 'Building monitoring solutions', 'Monitoring, Alerting, Dashboards', '[{"name": "Prometheus", "rating": 5}, {"name": "Grafana", "rating": 5}, {"name": "ELK Stack", "rating": 4}, {"name": "Python", "rating": 4}, {"name": "Alerting", "rating": 5}]'::jsonb),
('Dmitry Volkov', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400', 'Russia', 'Infrastructure Architect', 'Infrastructure', 'Designing infrastructure solutions', 'Infrastructure design, Cloud, Architecture', '[{"name": "Cloud Architecture", "rating": 5}, {"name": "AWS", "rating": 5}, {"name": "Infrastructure Design", "rating": 5}, {"name": "Terraform", "rating": 5}, {"name": "Networking", "rating": 4}]'::jsonb),
('Priya Reddy', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'India', 'Azure DevOps Engineer', 'Infrastructure', 'Microsoft Azure DevOps', 'Azure, DevOps, Pipelines', '[{"name": "Azure", "rating": 5}, {"name": "Azure DevOps", "rating": 5}, {"name": "PowerShell", "rating": 5}, {"name": "Terraform", "rating": 4}, {"name": "ARM Templates", "rating": 4}]'::jsonb),
('Finn O''Sullivan', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Ireland', 'GCP Engineer', 'Infrastructure', 'Google Cloud Platform specialist', 'GCP, Cloud, Infrastructure', '[{"name": "GCP", "rating": 5}, {"name": "Terraform", "rating": 5}, {"name": "Kubernetes", "rating": 5}, {"name": "Python", "rating": 4}, {"name": "CI/CD", "rating": 4}]'::jsonb),
('Luna Martinez', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Mexico', 'Database Administrator', 'Infrastructure', 'Database management and optimization', 'Database admin, Performance, Backup', '[{"name": "PostgreSQL", "rating": 5}, {"name": "MySQL", "rating": 5}, {"name": "Database Tuning", "rating": 5}, {"name": "Backup/Recovery", "rating": 5}, {"name": "SQL", "rating": 5}]'::jsonb),
('Andrei Popescu', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Romania', 'Systems Engineer', 'Infrastructure', 'Linux systems engineering', 'Linux, Systems, Automation', '[{"name": "Linux", "rating": 5}, {"name": "Bash", "rating": 5}, {"name": "System Administration", "rating": 5}, {"name": "Ansible", "rating": 4}, {"name": "Networking", "rating": 4}]'::jsonb),
('Samira Khatib', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', 'Lebanon', 'Automation Engineer', 'Infrastructure', 'Infrastructure automation specialist', 'Automation, IaC, Tools', '[{"name": "Ansible", "rating": 5}, {"name": "Terraform", "rating": 5}, {"name": "Python", "rating": 5}, {"name": "Automation", "rating": 5}, {"name": "Git", "rating": 4}]'::jsonb),
('Mateo Gonzalez', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'Colombia', 'Container Platform Engineer', 'Infrastructure', 'Container orchestration platforms', 'Containers, Kubernetes, Docker', '[{"name": "Kubernetes", "rating": 5}, {"name": "Docker", "rating": 5}, {"name": "Helm", "rating": 5}, {"name": "Container Security", "rating": 4}, {"name": "CI/CD", "rating": 4}]'::jsonb),
('Hana Kim', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', 'South Korea', 'Observability Engineer', 'Infrastructure', 'Building observability solutions', 'Observability, Tracing, Metrics', '[{"name": "OpenTelemetry", "rating": 5}, {"name": "Prometheus", "rating": 5}, {"name": "Jaeger", "rating": 4}, {"name": "Grafana", "rating": 5}, {"name": "ELK", "rating": 4}]'::jsonb),
('Rashid Al-Mahmoud', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', 'Qatar', 'Backup Engineer', 'Infrastructure', 'Disaster recovery and backup', 'Backup, DR, Recovery', '[{"name": "Backup Solutions", "rating": 5}, {"name": "Disaster Recovery", "rating": 5}, {"name": "Veeam", "rating": 4}, {"name": "Storage", "rating": 4}, {"name": "Scripting", "rating": 4}]'::jsonb),

-- More Specialized Engineers (136-155)
('Kristina Novak', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Slovenia', 'Search Engineer', 'Engineering', 'Building search and discovery features', 'Search, Elasticsearch, Relevance', '[{"name": "Elasticsearch", "rating": 5}, {"name": "Search", "rating": 5}, {"name": "Python", "rating": 4}, {"name": "Lucene", "rating": 4}, {"name": "Relevance", "rating": 5}]'::jsonb),
('Omar Farouk', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'Egypt', 'Video Streaming Engineer', 'Engineering', 'Live and on-demand video streaming', 'Video streaming, CDN, Encoding', '[{"name": "Video Streaming", "rating": 5}, {"name": "HLS", "rating": 5}, {"name": "FFmpeg", "rating": 5}, {"name": "CDN", "rating": 4}, {"name": "AWS Media", "rating": 4}]'::jsonb),
('Sophia Kowalski', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Poland', 'Payment Systems Engineer', 'Engineering', 'Building payment integrations', 'Payments, Fintech, Security', '[{"name": "Payment Systems", "rating": 5}, {"name": "PCI Compliance", "rating": 5}, {"name": "Java", "rating": 4}, {"name": "Security", "rating": 5}, {"name": "APIs", "rating": 5}]'::jsonb),
('Raj Kumar', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'India', 'IoT Engineer', 'Engineering', 'Internet of Things solutions', 'IoT, Embedded, Protocols', '[{"name": "IoT", "rating": 5}, {"name": "MQTT", "rating": 5}, {"name": "Embedded Systems", "rating": 4}, {"name": "Python", "rating": 4}, {"name": "C", "rating": 4}]'::jsonb),
('Elsa Andersson', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Sweden', 'Voice UI Engineer', 'Engineering', 'Voice interfaces and conversational AI', 'Voice UI, NLU, Conversational AI', '[{"name": "Voice UI", "rating": 5}, {"name": "NLU", "rating": 5}, {"name": "Python", "rating": 4}, {"name": "Alexa", "rating": 4}, {"name": "Dialogflow", "rating": 4}]'::jsonb),
('Tariq Mansour', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Palestine', 'AR/VR Developer', 'Engineering', 'Augmented and virtual reality', 'AR/VR, Unity, 3D', '[{"name": "Unity", "rating": 5}, {"name": "C#", "rating": 5}, {"name": "AR", "rating": 4}, {"name": "VR", "rating": 4}, {"name": "3D Development", "rating": 4}]'::jsonb),
('Isabelle Dubois', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'France', 'Robotics Engineer', 'Engineering', 'Robotics software development', 'Robotics, ROS, Automation', '[{"name": "ROS", "rating": 5}, {"name": "Python", "rating": 5}, {"name": "C++", "rating": 5}, {"name": "Robotics", "rating": 5}, {"name": "Computer Vision", "rating": 4}]'::jsonb),
('Javier Moreno', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Spain', 'Email Infrastructure Engineer', 'Engineering', 'Email delivery and infrastructure', 'Email, Deliverability, Infrastructure', '[{"name": "Email Infrastructure", "rating": 5}, {"name": "Postfix", "rating": 5}, {"name": "Deliverability", "rating": 5}, {"name": "DNS", "rating": 4}, {"name": "Python", "rating": 4}]'::jsonb),
('Zainab Ali', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Iraq', 'Localization Engineer', 'Engineering', 'Internationalization and localization', 'i18n, l10n, Translation', '[{"name": "Localization", "rating": 5}, {"name": "i18n", "rating": 5}, {"name": "Translation Management", "rating": 5}, {"name": "JavaScript", "rating": 4}, {"name": "Tools", "rating": 4}]'::jsonb),
('Klaus Wagner', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400', 'Germany', 'Accessibility Engineer', 'Engineering', 'Web accessibility specialist', 'Accessibility, WCAG, A11y', '[{"name": "Accessibility", "rating": 5}, {"name": "WCAG", "rating": 5}, {"name": "ARIA", "rating": 5}, {"name": "JavaScript", "rating": 4}, {"name": "Testing", "rating": 5}]'::jsonb),
('Amina Bakari', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'Tanzania', 'SEO Engineer', 'Marketing', 'Technical SEO and optimization', 'SEO, Technical SEO, Analytics', '[{"name": "SEO", "rating": 5}, {"name": "Technical SEO", "rating": 5}, {"name": "Google Analytics", "rating": 5}, {"name": "HTML", "rating": 4}, {"name": "JavaScript", "rating": 3}]'::jsonb),
('Erik Nilsson', 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400', 'Sweden', 'Build Systems Engineer', 'Engineering', 'Build tools and optimization', 'Build systems, Performance, Tools', '[{"name": "Bazel", "rating": 5}, {"name": "Build Optimization", "rating": 5}, {"name": "Python", "rating": 4}, {"name": "CI/CD", "rating": 5}, {"name": "C++", "rating": 4}]'::jsonb),
('Layla Husseini', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', 'Jordan', 'Integration Engineer', 'Engineering', 'System integrations and middleware', 'Integration, Middleware, APIs', '[{"name": "Integration", "rating": 5}, {"name": "ESB", "rating": 4}, {"name": "APIs", "rating": 5}, {"name": "MuleSoft", "rating": 4}, {"name": "Java", "rating": 4}]'::jsonb),
('Maxim Sokolov', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'Belarus', 'Firmware Engineer', 'Engineering', 'Embedded firmware development', 'Firmware, Embedded, C', '[{"name": "C", "rating": 5}, {"name": "Embedded Systems", "rating": 5}, {"name": "Firmware", "rating": 5}, {"name": "ARM", "rating": 4}, {"name": "Hardware", "rating": 4}]'::jsonb),
('Fatou Diop', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', 'Senegal', 'Chatbot Developer', 'Engineering', 'Conversational AI and chatbots', 'Chatbots, NLP, AI', '[{"name": "Chatbots", "rating": 5}, {"name": "NLP", "rating": 5}, {"name": "Python", "rating": 5}, {"name": "Dialogflow", "rating": 5}, {"name": "Node.js", "rating": 3}]'::jsonb),
('Vincent Leroy', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Belgium', 'Recommendation Systems Engineer', 'Engineering', 'Building recommendation algorithms', 'Recommendations, ML, Personalization', '[{"name": "Machine Learning", "rating": 5}, {"name": "Python", "rating": 5}, {"name": "Recommendation Systems", "rating": 5}, {"name": "Spark", "rating": 4}, {"name": "TensorFlow", "rating": 4}]'::jsonb),
('Amal Haddad', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Tunisia', 'ETL Developer', 'Data & Analytics', 'Data extraction and transformation', 'ETL, Data pipelines, Integration', '[{"name": "ETL", "rating": 5}, {"name": "SQL", "rating": 5}, {"name": "Python", "rating": 5}, {"name": "Informatica", "rating": 4}, {"name": "Data Integration", "rating": 5}]'::jsonb),
('Liam O''Connor', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', 'Ireland', 'Workflow Automation Engineer', 'Engineering', 'Business process automation', 'Automation, Workflows, RPA', '[{"name": "Workflow Automation", "rating": 5}, {"name": "RPA", "rating": 5}, {"name": "Python", "rating": 4}, {"name": "UiPath", "rating": 4}, {"name": "Process Design", "rating": 5}]'::jsonb),
('Nadia Popov', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Bulgaria', 'Fraud Detection Engineer', 'Engineering', 'Building fraud detection systems', 'Fraud detection, ML, Security', '[{"name": "Fraud Detection", "rating": 5}, {"name": "Machine Learning", "rating": 5}, {"name": "Python", "rating": 5}, {"name": "SQL", "rating": 5}, {"name": "Risk Analysis", "rating": 4}]'::jsonb),
('Ahmed Osman', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'Somalia', 'API Gateway Engineer', 'Engineering', 'API gateway and management', 'API Gateway, Kong, Security', '[{"name": "API Gateway", "rating": 5}, {"name": "Kong", "rating": 5}, {"name": "API Security", "rating": 5}, {"name": "Nginx", "rating": 4}, {"name": "Lua", "rating": 4}]'::jsonb),

-- More Leadership & Management (156-170)
('Sophia Wagner', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Austria', 'VP of Engineering', 'Leadership', 'Leading engineering organization', 'Leadership, Strategy, Organization', '[{"name": "Executive Leadership", "rating": 5}, {"name": "Strategy", "rating": 5}, {"name": "Team Building", "rating": 5}, {"name": "Budgeting", "rating": 5}, {"name": "Vision", "rating": 5}]'::jsonb),
('Roberto Silva', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Portugal', 'CTO', 'Leadership', 'Technology leadership and strategy', 'Technology strategy, Innovation, Leadership', '[{"name": "Technology Strategy", "rating": 5}, {"name": "Leadership", "rating": 5}, {"name": "Innovation", "rating": 5}, {"name": "Architecture", "rating": 4}, {"name": "Business Acumen", "rating": 5}]'::jsonb),
('Nina Larsen', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Denmark', 'Head of Product', 'Product', 'Product organization leadership', 'Product leadership, Strategy, Vision', '[{"name": "Product Leadership", "rating": 5}, {"name": "Strategy", "rating": 5}, {"name": "Vision", "rating": 5}, {"name": "Team Management", "rating": 5}, {"name": "Stakeholders", "rating": 5}]'::jsonb),
('Hassan Nour', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Sudan', 'Head of Design', 'Design', 'Design team leadership', 'Design leadership, Strategy, Culture', '[{"name": "Design Leadership", "rating": 5}, {"name": "Design Strategy", "rating": 5}, {"name": "Team Management", "rating": 5}, {"name": "Design Systems", "rating": 4}, {"name": "Vision", "rating": 5}]'::jsonb),
('Carla Rossi', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'Italy', 'VP of Product', 'Product', 'Product strategy and leadership', 'Product strategy, Leadership, Innovation', '[{"name": "Product Strategy", "rating": 5}, {"name": "Leadership", "rating": 5}, {"name": "Innovation", "rating": 5}, {"name": "Market Analysis", "rating": 5}, {"name": "P&L", "rating": 4}]'::jsonb),
('Viktor Novak', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400', 'Slovakia', 'Director of DevOps', 'Infrastructure', 'DevOps organization leadership', 'DevOps leadership, Strategy, Culture', '[{"name": "DevOps Leadership", "rating": 5}, {"name": "Strategy", "rating": 5}, {"name": "Cloud", "rating": 4}, {"name": "Team Building", "rating": 5}, {"name": "Process Improvement", "rating": 5}]'::jsonb),
('Amira Youssef', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Egypt', 'Director of QA', 'Quality', 'QA organization leadership', 'QA leadership, Strategy, Process', '[{"name": "QA Leadership", "rating": 5}, {"name": "Test Strategy", "rating": 5}, {"name": "Process Improvement", "rating": 5}, {"name": "Team Management", "rating": 5}, {"name": "Automation Strategy", "rating": 5}]'::jsonb),
('Patrick Lefevre', 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=400', 'France', 'Principal Engineer', 'Engineering', 'Technical leadership and architecture', 'Technical leadership, Architecture, Mentoring', '[{"name": "Technical Leadership", "rating": 5}, {"name": "Architecture", "rating": 5}, {"name": "Mentoring", "rating": 5}, {"name": "System Design", "rating": 5}, {"name": "Code Review", "rating": 5}]'::jsonb),
('Yara Khalil', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', 'Lebanon', 'Staff Engineer', 'Engineering', 'Senior technical leadership', 'Technical leadership, Design, Innovation', '[{"name": "System Design", "rating": 5}, {"name": "Technical Leadership", "rating": 5}, {"name": "Architecture", "rating": 5}, {"name": "Python", "rating": 5}, {"name": "Mentoring", "rating": 4}]'::jsonb),
('Gustav Eriksson', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'Sweden', 'Distinguished Engineer', 'Engineering', 'Distinguished technical fellow', 'Innovation, Architecture, Strategy', '[{"name": "Innovation", "rating": 5}, {"name": "Architecture", "rating": 5}, {"name": "Technical Strategy", "rating": 5}, {"name": "Thought Leadership", "rating": 5}, {"name": "Research", "rating": 5}]'::jsonb),
('Leila Mansouri', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'Iran', 'Technical Program Manager', 'Program Management', 'Managing complex technical programs', 'Program management, Coordination, Delivery', '[{"name": "Program Management", "rating": 5}, {"name": "Stakeholder Management", "rating": 5}, {"name": "Technical Coordination", "rating": 5}, {"name": "Risk Management", "rating": 5}, {"name": "Agile", "rating": 4}]'::jsonb),
('Marco Vitale', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Italy', 'Engineering Manager', 'Engineering', 'Managing engineering teams', 'Team management, Hiring, Coaching', '[{"name": "Team Management", "rating": 5}, {"name": "Hiring", "rating": 5}, {"name": "Coaching", "rating": 5}, {"name": "Performance Management", "rating": 5}, {"name": "Agile", "rating": 4}]'::jsonb),
('Hiba Nassar', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Palestine', 'Product Lead', 'Product', 'Leading product initiatives', 'Product leadership, Strategy, Execution', '[{"name": "Product Management", "rating": 5}, {"name": "Leadership", "rating": 5}, {"name": "Strategy", "rating": 5}, {"name": "Execution", "rating": 5}, {"name": "Analytics", "rating": 4}]'::jsonb),
('Anders Holm', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Norway', 'Design Director', 'Design', 'Creative direction and design leadership', 'Creative direction, Design, Leadership', '[{"name": "Creative Direction", "rating": 5}, {"name": "Design Leadership", "rating": 5}, {"name": "Brand", "rating": 5}, {"name": "Team Management", "rating": 5}, {"name": "Vision", "rating": 5}]'::jsonb),
('Yasmin Ahmed', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Bangladesh', 'Data Science Manager', 'Data & Analytics', 'Managing data science teams', 'DS management, Strategy, Hiring', '[{"name": "Data Science Management", "rating": 5}, {"name": "Strategy", "rating": 5}, {"name": "Team Building", "rating": 5}, {"name": "Machine Learning", "rating": 4}, {"name": "Analytics", "rating": 5}]'::jsonb),

-- Final Mix of Roles (171-200)
('Chen Wei', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'Taiwan', 'Junior Frontend Developer', 'Engineering', 'Learning frontend development', 'React, JavaScript, Learning', '[{"name": "React", "rating": 3}, {"name": "JavaScript", "rating": 3}, {"name": "HTML", "rating": 4}, {"name": "CSS", "rating": 3}, {"name": "Git", "rating": 3}]'::jsonb),
('Sofia Petrova', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', 'Bulgaria', 'Junior Backend Developer', 'Engineering', 'Starting career in backend', 'Java, Learning, APIs', '[{"name": "Java", "rating": 3}, {"name": "Spring Boot", "rating": 2}, {"name": "SQL", "rating": 3}, {"name": "REST API", "rating": 3}, {"name": "Git", "rating": 3}]'::jsonb),
('Luis Fernandez', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', 'Venezuela', 'Junior Full-Stack Developer', 'Engineering', 'Full-stack development trainee', 'Web development, Learning, React', '[{"name": "JavaScript", "rating": 3}, {"name": "React", "rating": 3}, {"name": "Node.js", "rating": 2}, {"name": "MongoDB", "rating": 2}, {"name": "Git", "rating": 3}]'::jsonb),
('Aisha Kamara', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Sierra Leone', 'Technical Support Engineer', 'Support', 'Providing technical customer support', 'Technical support, Troubleshooting, Customer service', '[{"name": "Technical Support", "rating": 5}, {"name": "Troubleshooting", "rating": 5}, {"name": "Customer Service", "rating": 5}, {"name": "Linux", "rating": 3}, {"name": "Networking", "rating": 3}]'::jsonb),
('Paolo Greco', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'Greece', 'Solutions Engineer', 'Sales Engineering', 'Pre-sales technical expertise', 'Pre-sales, Demos, Technical presentations', '[{"name": "Pre-sales", "rating": 5}, {"name": "Demos", "rating": 5}, {"name": "Technical Presentations", "rating": 5}, {"name": "Solution Architecture", "rating": 4}, {"name": "Customer Engagement", "rating": 5}]'::jsonb),
('Fatima Diallo', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Guinea', 'Customer Success Engineer', 'Customer Success', 'Technical customer success', 'Customer success, Onboarding, Training', '[{"name": "Customer Success", "rating": 5}, {"name": "Onboarding", "rating": 5}, {"name": "Training", "rating": 5}, {"name": "Technical Support", "rating": 4}, {"name": "APIs", "rating": 3}]'::jsonb),
('Tomas Novak', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'Czech Republic', 'Site Reliability Engineer', 'Infrastructure', 'Production reliability', 'SRE, Production, Monitoring', '[{"name": "SRE", "rating": 5}, {"name": "Production Support", "rating": 5}, {"name": "Monitoring", "rating": 5}, {"name": "Kubernetes", "rating": 4}, {"name": "Python", "rating": 4}]'::jsonb),
('Mariam Diab', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Syria', 'Compliance Engineer', 'Compliance', 'Security and compliance', 'Compliance, Security, Auditing', '[{"name": "Compliance", "rating": 5}, {"name": "Security Auditing", "rating": 5}, {"name": "GDPR", "rating": 5}, {"name": "SOC 2", "rating": 4}, {"name": "Risk Assessment", "rating": 5}]'::jsonb),
('Jens Hansen', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Denmark', 'Performance Engineer', 'Engineering', 'Application performance optimization', 'Performance, Optimization, Profiling', '[{"name": "Performance Optimization", "rating": 5}, {"name": "Profiling", "rating": 5}, {"name": "Load Testing", "rating": 5}, {"name": "Java", "rating": 4}, {"name": "Monitoring", "rating": 5}]'::jsonb),
('Zara Hussein', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'Somalia', 'Incident Manager', 'Operations', 'Managing production incidents', 'Incident management, Communication, Resolution', '[{"name": "Incident Management", "rating": 5}, {"name": "Communication", "rating": 5}, {"name": "Problem Solving", "rating": 5}, {"name": "ITIL", "rating": 4}, {"name": "Documentation", "rating": 5}]'::jsonb),
('Nikolai Volkov', 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400', 'Russia', 'Release Manager', 'Operations', 'Managing software releases', 'Release management, Coordination, Planning', '[{"name": "Release Management", "rating": 5}, {"name": "Project Coordination", "rating": 5}, {"name": "Planning", "rating": 5}, {"name": "Risk Management", "rating": 5}, {"name": "Communication", "rating": 5}]'::jsonb),
('Gabriella Santos', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'Brazil', 'Change Manager', 'Operations', 'Change management processes', 'Change management, ITIL, Process', '[{"name": "Change Management", "rating": 5}, {"name": "ITIL", "rating": 5}, {"name": "Process Management", "rating": 5}, {"name": "Risk Assessment", "rating": 5}, {"name": "Communication", "rating": 5}]'::jsonb),
('Karim Benzema', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Algeria', 'Configuration Manager', 'Operations', 'Configuration and asset management', 'Configuration management, CMDB, Assets', '[{"name": "Configuration Management", "rating": 5}, {"name": "CMDB", "rating": 5}, {"name": "Asset Management", "rating": 5}, {"name": "ITIL", "rating": 4}, {"name": "Automation", "rating": 4}]'::jsonb),
('Elena Rossi', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400', 'Italy', 'Knowledge Manager', 'Operations', 'Knowledge base and documentation', 'Knowledge management, Documentation, Training', '[{"name": "Knowledge Management", "rating": 5}, {"name": "Documentation", "rating": 5}, {"name": "Training", "rating": 5}, {"name": "Content Management", "rating": 5}, {"name": "Process", "rating": 4}]'::jsonb),
('Muhammad Ali', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Pakistan', 'Service Desk Manager', 'Support', 'Managing service desk operations', 'Service desk, Team management, ITIL', '[{"name": "Service Desk Management", "rating": 5}, {"name": "Team Management", "rating": 5}, {"name": "ITIL", "rating": 5}, {"name": "Customer Service", "rating": 5}, {"name": "Metrics", "rating": 5}]'::jsonb),
('Ines Martinez', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Spain', 'IT Operations Manager', 'Operations', 'IT operations leadership', 'IT operations, Management, Strategy', '[{"name": "IT Operations", "rating": 5}, {"name": "Team Management", "rating": 5}, {"name": "Strategy", "rating": 5}, {"name": "Budgeting", "rating": 4}, {"name": "ITIL", "rating": 5}]'::jsonb),
('Wei Chen', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400', 'China', 'Capacity Planner', 'Operations', 'Infrastructure capacity planning', 'Capacity planning, Forecasting, Analysis', '[{"name": "Capacity Planning", "rating": 5}, {"name": "Forecasting", "rating": 5}, {"name": "Data Analysis", "rating": 5}, {"name": "Monitoring", "rating": 4}, {"name": "Cloud", "rating": 4}]'::jsonb),
('Amara Nkomo', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400', 'Zimbabwe', 'Vendor Manager', 'Operations', 'Managing technology vendors', 'Vendor management, Contracts, Negotiation', '[{"name": "Vendor Management", "rating": 5}, {"name": "Contract Negotiation", "rating": 5}, {"name": "Relationship Management", "rating": 5}, {"name": "SLA Management", "rating": 5}, {"name": "Procurement", "rating": 4}]'::jsonb),
('Boris Ivanov', 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400', 'Ukraine', 'IT Asset Manager', 'Operations', 'IT asset lifecycle management', 'Asset management, Inventory, Lifecycle', '[{"name": "Asset Management", "rating": 5}, {"name": "Inventory Management", "rating": 5}, {"name": "Lifecycle Management", "rating": 5}, {"name": "Procurement", "rating": 4}, {"name": "Compliance", "rating": 4}]'::jsonb),
('Laila Farah', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400', 'Lebanon', 'IT Procurement Specialist', 'Operations', 'Technology procurement', 'Procurement, Sourcing, Negotiation', '[{"name": "IT Procurement", "rating": 5}, {"name": "Sourcing", "rating": 5}, {"name": "Negotiation", "rating": 5}, {"name": "Vendor Management", "rating": 5}, {"name": "Cost Analysis", "rating": 5}]'::jsonb),
('Rafael Costa', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400', 'Portugal', 'IT Auditor', 'Compliance', 'IT systems auditing', 'IT auditing, Compliance, Risk', '[{"name": "IT Auditing", "rating": 5}, {"name": "Compliance", "rating": 5}, {"name": "Risk Assessment", "rating": 5}, {"name": "Security Auditing", "rating": 5}, {"name": "Reporting", "rating": 5}]'::jsonb),
('Nour Hassan', 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400', 'Egypt', 'IT Risk Manager', 'Risk Management', 'IT risk management', 'Risk management, Assessment, Mitigation', '[{"name": "Risk Management", "rating": 5}, {"name": "Risk Assessment", "rating": 5}, {"name": "Risk Mitigation", "rating": 5}, {"name": "Compliance", "rating": 5}, {"name": "Reporting", "rating": 5}]'::jsonb),
('Mikkel Jensen', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400', 'Denmark', 'Business Continuity Manager', 'Operations', 'Business continuity planning', 'BC/DR, Planning, Testing', '[{"name": "Business Continuity", "rating": 5}, {"name": "Disaster Recovery", "rating": 5}, {"name": "Planning", "rating": 5}, {"name": "Testing", "rating": 5}, {"name": "Risk Management", "rating": 5}]'::jsonb),
('Zoe Papadopoulos', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400', 'Greece', 'IT Trainer', 'Training', 'Technical training and enablement', 'Training, Education, Enablement', '[{"name": "Technical Training", "rating": 5}, {"name": "Curriculum Design", "rating": 5}, {"name": "Presentation", "rating": 5}, {"name": "E-learning", "rating": 4}, {"name": "Assessment", "rating": 4}]'::jsonb),
('Ibrahim Nasser', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400', 'Kuwait', 'Learning & Development Manager', 'Training', 'Technology learning programs', 'L&D, Training programs, Strategy', '[{"name": "Learning & Development", "rating": 5}, {"name": "Training Strategy", "rating": 5}, {"name": "Program Management", "rating": 5}, {"name": "Leadership Development", "rating": 5}, {"name": "Coaching", "rating": 5}]'::jsonb),
('Petra Novotna', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400', 'Slovakia', 'IT Project Manager', 'Project Management', 'Managing IT projects', 'Project management, Planning, Delivery', '[{"name": "Project Management", "rating": 5}, {"name": "Planning", "rating": 5}, {"name": "Agile", "rating": 5}, {"name": "Stakeholder Management", "rating": 5}, {"name": "Risk Management", "rating": 5}]'::jsonb),
('Omar Al-Farsi', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400', 'Oman', 'IT Portfolio Manager', 'Project Management', 'IT portfolio management', 'Portfolio management, Strategy, Prioritization', '[{"name": "Portfolio Management", "rating": 5}, {"name": "Strategy", "rating": 5}, {"name": "Prioritization", "rating": 5}, {"name": "Resource Management", "rating": 5}, {"name": "Financial Management", "rating": 5}]'::jsonb),
('Carolina Lopez', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400', 'Chile', 'PMO Lead', 'Project Management', 'Project Management Office leadership', 'PMO, Governance, Standards', '[{"name": "PMO Leadership", "rating": 5}, {"name": "Governance", "rating": 5}, {"name": "Standards", "rating": 5}, {"name": "Process Improvement", "rating": 5}, {"name": "Reporting", "rating": 5}]'::jsonb),
('Yusuf Khan', 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400', 'India', 'Enterprise Architect', 'Architecture', 'Enterprise-wide technology architecture', 'Enterprise architecture, Strategy, Transformation', '[{"name": "Enterprise Architecture", "rating": 5}, {"name": "TOGAF", "rating": 5}, {"name": "Strategy", "rating": 5}, {"name": "Digital Transformation", "rating": 5}, {"name": "Governance", "rating": 5}]'::jsonb),
('Anastasia Petrov', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400', 'Russia', 'Innovation Manager', 'Innovation', 'Driving technology innovation', 'Innovation, Research, Strategy', '[{"name": "Innovation Management", "rating": 5}, {"name": "Research", "rating": 5}, {"name": "Strategy", "rating": 5}, {"name": "Emerging Tech", "rating": 5}, {"name": "Change Management", "rating": 5}]'::jsonb);
